### ISSUE TITLE
Search button for enrollSubjects and Enlisting subjects

### ISSUE THREAD

**Issue by Crunchies3** [Crunchies3/StudentAccounting#17]
https://github.com/Crunchies3/StudentAccounting/blob/master/prj_StudentAccounting/frm_sEnrollSubject.vb

Paki implement ko sa search button goy katong with auto complete. then kung mo select siyag subject sa table  tapos pisliton ang enlist na button kay dapat ma enroll ang student ato na subject. Mo warning dapat kung already enrolled na siya

**Comment by kixks** [comment]
Fixed
