### ISSUE TITLE
Display Available subjects for enrollment

### ISSUE THREAD

**Issue by Crunchies3** [Crunchies3/StudentAccounting#4]
https://github.com/Crunchies3/StudentAccounting/blob/3f05c6c89af7ca51136487ab1e4397c02ecdaf39/prj_StudentAccounting/frm_sEnrollSubject.vb

kani na file i edit goy.  dapat i display niya ang available na subjects nga ka Year level sa isa ka student. 
ex.  3rd year student. 3rd year subject rapud ang i display

**Comment by kixks** [comment]
Pixed. naa na sa pr lods hahahaha
