### ISSUE TITLE
Admin client. Search Functions

### ISSUE THREAD

**Issue by Crunchies3** [Crunchies3/StudentAccounting#53]
![image](https://github.com/Crunchies3/StudentAccounting/assets/113993166/9b4d6437-bdbb-49e5-b482-13094bd91b31)

- [ ] usabon from lastname ang i search to ID. same sa frm_aStudent, frm_aDashboard_v2, ug frm_aTeacher.
- [ ] buhatan ug search funtion ang frm_aSubjectList, ug frm_aFees
- sa subject kay by title
- sa fee kay by description

**Comment by kixks** [comment]
unsa nga id cy stgudent id? o id lang?
